# Trigger the workflow on any push or pull request to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Define the operating systems to run the build on using a matrix strategy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.8 environment using the 'setup-python' GitHub Action
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install project dependencies using pipenv (Python dependency manager)
      - name: Install dependencies
        run: |
          pipenv install

      # Step 4: Run tests using pytest to ensure code integrity before deployment
      - name: Run tests
        run: |
          pytest

      # Step 5: Deployment step
      - name: Deploy
        run: |
          echo "Deploying to production server"
          # Add your deployment commands here 
